# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Asar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Asar
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'	
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'KeychainAccess', '4.2.1'
	pod 'SwiftGen', '6.5.1'
	pod 'MaterialActivityIndicator'
	pod 'SnapKit', '~> 5.6.0'
	pod 'SkyFloatingLabelTextField', '~> 3.0'
	pod 'DropDown'

	pod 'iOSUtilitiesSource', :git => 'https://github.com/hasnine/iOSUtilitiesSource.git'
end
